package database;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMarshalling;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName = "tasks")
public class TaskAdminPanel {

	private String mID;
	private String mTitle;
	private String mBody;
	private UserAdminPanel mTaskOpener;
	private ArrayList<UserAdminPanel> mVolunteers;
	private Set<String> mUnParsedVolunteers;
	private String mAttachedUserToTaskID;
	
	public TaskAdminPanel() {
		mVolunteers = new ArrayList<UserAdminPanel>();
	}
	public TaskAdminPanel (String title, String body, UserAdminPanel taskOpener) {
		setTitle(title);
		mBody = body;
		mTaskOpener = taskOpener;
		mVolunteers = new ArrayList<UserAdminPanel>();
		mUnParsedVolunteers = new HashSet<String>();
				
	}
	
	@DynamoDBHashKey(attributeName = "Id")
	@DynamoDBAutoGeneratedKey
	public String getID() {
		return mID;
	}
	public void setID(String id){
		mID = id;
	}
	
	@DynamoDBMarshalling (marshallerClass = UserAdminPanel.class)
	public UserAdminPanel getTaskOpener() {
		return mTaskOpener;
	}
	public void setTaskOpener(UserAdminPanel taskOpener) {
		mTaskOpener = taskOpener;
	}
	
	@DynamoDBAttribute(attributeName = "title")
	public String getTitle() {
		return mTitle;
	}
	public void setTitle(String title) {
		mTitle = title;
	}
	
	@DynamoDBAttribute(attributeName = "body")
	public String getBody() {
		return mBody;
	}
	public void setBody(String body) {
		mBody = body;
	}
	
	@DynamoDBAttribute(attributeName = "volunteers")
	public Set<String> getUnParsedVolunteers() {
		return mUnParsedVolunteers;
	}
	public void setUnParsedVolunteers(Set<String> volunteers) {
		mUnParsedVolunteers = volunteers;
		parseVolunteers();
	}
	
	public void updateUserToDB() {
		 try {
				DynamoDBManager.init();
				DynamoDBManager.addTaskToDB(this);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
	}
	
	@DynamoDBAttribute(attributeName = "attachedUserToTask")
	public  String getAttachedUserToTask() {
		return mAttachedUserToTaskID;
	}
	public  void setAttachedUserToTask(String attchedUserID) {
		mAttachedUserToTaskID = attchedUserID;
	}
	
	public void addVolunteer (UserAdminPanel volunteer) {
		mVolunteers.add(volunteer);
		mUnParsedVolunteers.add(volunteer.marshall(volunteer));
	}
	
	public ArrayList<UserAdminPanel> volunteers() {
		return mVolunteers;
	}
	
	
	private void parseVolunteers() {
		Class<UserAdminPanel> clazz = null;
		for (String str : mUnParsedVolunteers) {
			UserAdminPanel user = new UserAdminPanel().unmarshall(clazz, str);
				mVolunteers.add(user);
		}		
	}
	
}
